"""empty message

Revision ID: 194f4ccf54ac
Revises: c605c4fcdbb8
Create Date: 2023-03-01 04:33:14.370547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194f4ccf54ac'
down_revision = 'c605c4fcdbb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_decision_criteria_details_2maptoperson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_importance', sa.String(length=20), nullable=False))
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_details_2maptoperson_client_importance'), ['client_importance'], unique=False)
        batch_op.drop_constraint('fk_ads_decision_criteria_details_2maptoperson_ads_relationships_details_fk_ads_relationships_details', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_ads_decision_criteria_details_2maptoperson_ads_relationships_details_fk_ads_relationships_details'), 'ads_relationships_details', ['ads_relationships_details_fk'], ['_pk'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_decision_criteria_details_2maptoperson', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ads_decision_criteria_details_2maptoperson_ads_relationships_details_fk_ads_relationships_details'), type_='foreignkey')
        batch_op.create_foreign_key('fk_ads_decision_criteria_details_2maptoperson_ads_relationships_details_fk_ads_relationships_details', 'ads_relationships_details', ['ads_relationships_details_fk'], ['_pk'])
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_details_2maptoperson_client_importance'))
        batch_op.drop_column('client_importance')

    # ### end Alembic commands ###
