"""empty message

Revision ID: 200f1f96c1d5
Revises: 194f4ccf54ac
Create Date: 2023-03-05 21:14:57.399394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200f1f96c1d5'
down_revision = '194f4ccf54ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_decision_criteria_details_2maptoperson', schema=None) as batch_op:
        batch_op.alter_column('ads_relationships_details_fk',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_decision_criteria_details_2maptoperson', schema=None) as batch_op:
        batch_op.alter_column('ads_relationships_details_fk',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###
