"""empty message

Revision ID: 3ae614995200
Revises: 9ed0124c5e8e
Create Date: 2023-03-23 05:25:57.978379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae614995200'
down_revision = '9ed0124c5e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads_general_data_version',
    sa.Column('_pk', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('_updated_by', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('_updated_at', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('_disabled', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('sales_project_fk', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('decisive_event', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('competition', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('potential_problems', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('team_members', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('client_company', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('_pk', 'transaction_id', name=op.f('pk_ads_general_data_version'))
    )
    with op.batch_alter_table('ads_general_data_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_general_data_version__disabled'), ['_disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_general_data_version__updated_by'), ['_updated_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_general_data_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_general_data_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_general_data_version_sales_project_fk'), ['sales_project_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_general_data_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('transaction',
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    with op.batch_alter_table('ads_general_data_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_general_data_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ads_general_data_version_sales_project_fk'))
        batch_op.drop_index(batch_op.f('ix_ads_general_data_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_ads_general_data_version_end_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ads_general_data_version__updated_by'))
        batch_op.drop_index(batch_op.f('ix_ads_general_data_version__disabled'))

    op.drop_table('ads_general_data_version')
    # ### end Alembic commands ###
