"""empty message

Revision ID: 8cd9cf010bcb
Revises: 8d59551769fa
Create Date: 2023-02-28 05:33:47.303172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd9cf010bcb'
down_revision = '8d59551769fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads_decision_criteria',
    sa.Column('_pk', sa.String(length=36), nullable=False),
    sa.Column('_updated_by', sa.String(length=100), nullable=False),
    sa.Column('_updated_at', sa.DateTime(), nullable=False),
    sa.Column('_disabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('_pk', name=op.f('pk_ads_decision_criteria'))
    )
    with op.batch_alter_table('ads_decision_criteria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria__disabled'), ['_disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria__updated_by'), ['_updated_by'], unique=False)

    op.create_table('ads_decision_criteria_details_1criterialist',
    sa.Column('_pk', sa.String(length=36), nullable=False),
    sa.Column('_updated_by', sa.String(length=100), nullable=False),
    sa.Column('_updated_at', sa.DateTime(), nullable=False),
    sa.Column('_disabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('_pk', name=op.f('pk_ads_decision_criteria_details_1criterialist'))
    )
    with op.batch_alter_table('ads_decision_criteria_details_1criterialist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_details_1criterialist__disabled'), ['_disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_details_1criterialist__updated_by'), ['_updated_by'], unique=False)

    op.create_table('ads_decision_criteria_details_2maptoperson',
    sa.Column('_pk', sa.String(length=36), nullable=False),
    sa.Column('_updated_by', sa.String(length=100), nullable=False),
    sa.Column('_updated_at', sa.DateTime(), nullable=False),
    sa.Column('_disabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('_pk', name=op.f('pk_ads_decision_criteria_details_2maptoperson'))
    )
    with op.batch_alter_table('ads_decision_criteria_details_2maptoperson', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_details_2maptoperson__disabled'), ['_disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_details_2maptoperson__updated_by'), ['_updated_by'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_decision_criteria_details_2maptoperson', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_details_2maptoperson__updated_by'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_details_2maptoperson__disabled'))

    op.drop_table('ads_decision_criteria_details_2maptoperson')
    with op.batch_alter_table('ads_decision_criteria_details_1criterialist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_details_1criterialist__updated_by'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_details_1criterialist__disabled'))

    op.drop_table('ads_decision_criteria_details_1criterialist')
    with op.batch_alter_table('ads_decision_criteria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria__updated_by'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria__disabled'))

    op.drop_table('ads_decision_criteria')
    # ### end Alembic commands ###
