"""empty message

Revision ID: 8cf38fde5734
Revises: d45f91162cb9
Create Date: 2023-02-28 14:30:30.511327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf38fde5734'
down_revision = 'd45f91162cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_decision_criteria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.String(length=100), nullable=False))
        batch_op.drop_index('ix_ads_decision_criteria_name')
        batch_op.drop_index('ix_ads_decision_criteria_our_status')
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_remarks'), ['remarks'], unique=False)
        batch_op.drop_column('name')
        batch_op.drop_column('our_status')

    with op.batch_alter_table('ads_decision_criteria_details_1criterialist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ads_decision_criteria_fk', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('our_status', sa.String(length=20), nullable=False))
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_details_1criterialist_ads_decision_criteria_fk'), ['ads_decision_criteria_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_details_1criterialist_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_details_1criterialist_our_status'), ['our_status'], unique=False)
        batch_op.create_unique_constraint('uix_name_per_solution', ['name', 'ads_decision_criteria_fk'])
        batch_op.create_foreign_key(batch_op.f('fk_ads_decision_criteria_details_1criterialist_ads_decision_criteria_fk_ads_decision_criteria'), 'ads_decision_criteria', ['ads_decision_criteria_fk'], ['_pk'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_decision_criteria_details_1criterialist', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ads_decision_criteria_details_1criterialist_ads_decision_criteria_fk_ads_decision_criteria'), type_='foreignkey')
        batch_op.drop_constraint('uix_name_per_solution', type_='unique')
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_details_1criterialist_our_status'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_details_1criterialist_name'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_details_1criterialist_ads_decision_criteria_fk'))
        batch_op.drop_column('our_status')
        batch_op.drop_column('name')
        batch_op.drop_column('ads_decision_criteria_fk')

    with op.batch_alter_table('ads_decision_criteria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('our_status', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_remarks'))
        batch_op.create_index('ix_ads_decision_criteria_our_status', ['our_status'], unique=False)
        batch_op.create_index('ix_ads_decision_criteria_name', ['name'], unique=False)
        batch_op.drop_column('remarks')

    # ### end Alembic commands ###
