"""empty message

Revision ID: 8d59551769fa
Revises: c5f710032056
Create Date: 2023-02-23 17:05:30.647244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d59551769fa'
down_revision = 'c5f710032056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_relationships_details', schema=None) as batch_op:
        batch_op.drop_constraint('uix_name_per_org_map', type_='unique')
        batch_op.create_unique_constraint('uix_name_per_relationships', ['name', 'ads_relationships_fk'])

    with op.batch_alter_table('ads_solution_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('strength', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('feature_type', sa.String(length=20), nullable=False))
        batch_op.create_index(batch_op.f('ix_ads_solution_details_feature_type'), ['feature_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_solution_details_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_solution_details_strength'), ['strength'], unique=False)
        batch_op.create_unique_constraint('uix_name_per_solution', ['name', 'ads_solution_fk'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_solution_details', schema=None) as batch_op:
        batch_op.drop_constraint('uix_name_per_solution', type_='unique')
        batch_op.drop_index(batch_op.f('ix_ads_solution_details_strength'))
        batch_op.drop_index(batch_op.f('ix_ads_solution_details_name'))
        batch_op.drop_index(batch_op.f('ix_ads_solution_details_feature_type'))
        batch_op.drop_column('feature_type')
        batch_op.drop_column('strength')
        batch_op.drop_column('name')

    with op.batch_alter_table('ads_relationships_details', schema=None) as batch_op:
        batch_op.drop_constraint('uix_name_per_relationships', type_='unique')
        batch_op.create_unique_constraint('uix_name_per_org_map', ['name', 'ads_relationships_fk'])

    # ### end Alembic commands ###
