"""empty message

Revision ID: 9ba3cfcb2fa7
Revises: d24e4a8eaaa2
Create Date: 2023-03-23 06:08:14.513853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba3cfcb2fa7'
down_revision = 'd24e4a8eaaa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads_revenue_version',
    sa.Column('_pk', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('_updated_by', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('_updated_at', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('_disabled', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('sales_project_fk', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('remarks', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('max_expected', sa.Float(), autoincrement=False, nullable=False),
    sa.Column('min_expected', sa.Float(), autoincrement=False, nullable=False),
    sa.Column('allocated_budget', sa.Float(), autoincrement=False, nullable=False),
    sa.Column('customer_min_expectation', sa.Float(), autoincrement=False, nullable=False),
    sa.Column('customer_max_expectation', sa.Float(), autoincrement=False, nullable=False),
    sa.Column('market_price', sa.Float(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('_pk', 'transaction_id', name=op.f('pk_ads_revenue_version'))
    )
    with op.batch_alter_table('ads_revenue_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_revenue_version__disabled'), ['_disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_revenue_version__updated_by'), ['_updated_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_revenue_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_revenue_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_revenue_version_sales_project_fk'), ['sales_project_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_revenue_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('ads_relationships_details_version', schema=None) as batch_op:
        batch_op.alter_column('_updated_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('_updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('_disabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('ads_relationships_fk',
               existing_type=sa.VARCHAR(length=36),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=36),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('change_adaptability',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('our_status_in_relation',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('contact_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               autoincrement=False)

    with op.batch_alter_table('ads_relationships_version', schema=None) as batch_op:
        batch_op.alter_column('_updated_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('_updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('_disabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('sales_project_fk',
               existing_type=sa.VARCHAR(length=36),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('remarks',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               autoincrement=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_relationships_version', schema=None) as batch_op:
        batch_op.alter_column('remarks',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('sales_project_fk',
               existing_type=sa.VARCHAR(length=36),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('_disabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('_updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('_updated_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               autoincrement=False)

    with op.batch_alter_table('ads_relationships_details_version', schema=None) as batch_op:
        batch_op.alter_column('contact_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('our_status_in_relation',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('change_adaptability',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=36),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('ads_relationships_fk',
               existing_type=sa.VARCHAR(length=36),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('_disabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('_updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('_updated_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               autoincrement=False)

    with op.batch_alter_table('ads_revenue_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_revenue_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ads_revenue_version_sales_project_fk'))
        batch_op.drop_index(batch_op.f('ix_ads_revenue_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_ads_revenue_version_end_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ads_revenue_version__updated_by'))
        batch_op.drop_index(batch_op.f('ix_ads_revenue_version__disabled'))

    op.drop_table('ads_revenue_version')
    # ### end Alembic commands ###
