"""empty message

Revision ID: ac9d78395fb2
Revises: 9451dca3fa40
Create Date: 2023-03-31 05:17:51.243417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9d78395fb2'
down_revision = '9451dca3fa40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_decision_criteria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), nullable=True))

    with op.batch_alter_table('ads_decision_criteria_details_1criterialist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), nullable=True))

    with op.batch_alter_table('ads_decision_criteria_details_1criterialist_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), autoincrement=False, nullable=True))

    with op.batch_alter_table('ads_decision_criteria_details_2maptoperson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), nullable=True))

    with op.batch_alter_table('ads_decision_criteria_details_2maptoperson_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), autoincrement=False, nullable=True))

    with op.batch_alter_table('ads_decision_criteria_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), autoincrement=False, nullable=True))

    with op.batch_alter_table('ads_evaluation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), nullable=True))

    with op.batch_alter_table('ads_evaluation_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), autoincrement=False, nullable=True))

    with op.batch_alter_table('ads_general_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), nullable=True))

    with op.batch_alter_table('ads_general_data_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), autoincrement=False, nullable=True))

    with op.batch_alter_table('ads_org_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), nullable=True))

    with op.batch_alter_table('ads_org_map_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), nullable=True))

    with op.batch_alter_table('ads_org_map_details_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), autoincrement=False, nullable=True))

    with op.batch_alter_table('ads_org_map_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), autoincrement=False, nullable=True))

    with op.batch_alter_table('ads_relationships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), nullable=True))

    with op.batch_alter_table('ads_relationships_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), nullable=True))

    with op.batch_alter_table('ads_relationships_details_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), autoincrement=False, nullable=True))

    with op.batch_alter_table('ads_relationships_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), autoincrement=False, nullable=True))

    with op.batch_alter_table('ads_revenue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), nullable=True))

    with op.batch_alter_table('ads_revenue_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), autoincrement=False, nullable=True))

    with op.batch_alter_table('ads_solution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), nullable=True))

    with op.batch_alter_table('ads_solution_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), nullable=True))

    with op.batch_alter_table('ads_solution_details_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), autoincrement=False, nullable=True))

    with op.batch_alter_table('ads_solution_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), autoincrement=False, nullable=True))

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), nullable=True))

    with op.batch_alter_table('salesproject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), nullable=True))

    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_useless_to_keep_history', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    with op.batch_alter_table('salesproject', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    with op.batch_alter_table('ads_solution_version', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    with op.batch_alter_table('ads_solution_details_version', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    with op.batch_alter_table('ads_solution_details', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    with op.batch_alter_table('ads_solution', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    with op.batch_alter_table('ads_revenue_version', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    with op.batch_alter_table('ads_revenue', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    with op.batch_alter_table('ads_relationships_version', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    with op.batch_alter_table('ads_relationships_details_version', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    with op.batch_alter_table('ads_relationships_details', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    with op.batch_alter_table('ads_relationships', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    with op.batch_alter_table('ads_org_map_version', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    with op.batch_alter_table('ads_org_map_details_version', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    with op.batch_alter_table('ads_org_map_details', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    with op.batch_alter_table('ads_org_map', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    with op.batch_alter_table('ads_general_data_version', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    with op.batch_alter_table('ads_general_data', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    with op.batch_alter_table('ads_evaluation_version', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    with op.batch_alter_table('ads_evaluation', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    with op.batch_alter_table('ads_decision_criteria_version', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    with op.batch_alter_table('ads_decision_criteria_details_2maptoperson_version', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    with op.batch_alter_table('ads_decision_criteria_details_2maptoperson', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    with op.batch_alter_table('ads_decision_criteria_details_1criterialist_version', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    with op.batch_alter_table('ads_decision_criteria_details_1criterialist', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    with op.batch_alter_table('ads_decision_criteria', schema=None) as batch_op:
        batch_op.drop_column('_useless_to_keep_history')

    # ### end Alembic commands ###
