"""empty message

Revision ID: b1650749c462
Revises: 
Create Date: 2023-02-19 17:25:03.545002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1650749c462'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('_pk', sa.String(length=36), nullable=False),
    sa.Column('_updated_by', sa.String(length=100), nullable=False),
    sa.Column('_updated_at', sa.DateTime(), nullable=False),
    sa.Column('_disabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('_pk', name=op.f('pk_company'))
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company__disabled'), ['_disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_company__updated_by'), ['_updated_by'], unique=False)

    op.create_table('salesproject',
    sa.Column('_pk', sa.String(length=36), nullable=False),
    sa.Column('_updated_by', sa.String(length=100), nullable=False),
    sa.Column('_updated_at', sa.DateTime(), nullable=False),
    sa.Column('_disabled', sa.Boolean(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('_pk', name=op.f('pk_salesproject'))
    )
    with op.batch_alter_table('salesproject', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salesproject__disabled'), ['_disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_salesproject__updated_by'), ['_updated_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_salesproject_code'), ['code'], unique=True)

    op.create_table('solution',
    sa.Column('_pk', sa.String(length=36), nullable=False),
    sa.Column('_updated_by', sa.String(length=100), nullable=False),
    sa.Column('_updated_at', sa.DateTime(), nullable=False),
    sa.Column('_disabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('_pk', name=op.f('pk_solution'))
    )
    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solution__disabled'), ['_disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_solution__updated_by'), ['_updated_by'], unique=False)

    op.create_table('ads_evaluation',
    sa.Column('_pk', sa.String(length=36), nullable=False),
    sa.Column('_updated_by', sa.String(length=100), nullable=False),
    sa.Column('_updated_at', sa.DateTime(), nullable=False),
    sa.Column('_disabled', sa.Boolean(), nullable=False),
    sa.Column('sales_project_fk', sa.String(length=36), nullable=False),
    sa.Column('remarks', sa.String(length=100), nullable=True),
    sa.Column('_final_applicability', sa.String(length=10), nullable=True),
    sa.Column('_customer_business', sa.String(length=10), nullable=True),
    sa.Column('_customer_financials', sa.String(length=10), nullable=True),
    sa.Column('_access_to_funds', sa.String(length=10), nullable=True),
    sa.Column('_decisive_event', sa.String(length=10), nullable=True),
    sa.Column('_formal_decision_making_criteria', sa.String(length=10), nullable=True),
    sa.Column('_solution_matching', sa.String(length=10), nullable=True),
    sa.Column('_resources_required_to_sell', sa.String(length=10), nullable=True),
    sa.Column('_current_relation_with_customer', sa.String(length=10), nullable=True),
    sa.Column('_value_of_business_proposal', sa.String(length=10), nullable=True),
    sa.Column('_internal_support', sa.String(length=10), nullable=True),
    sa.Column('_credibility', sa.String(length=10), nullable=True),
    sa.Column('_cultural_compatibility', sa.String(length=10), nullable=True),
    sa.Column('_approach_decision_making_criteria', sa.String(length=10), nullable=True),
    sa.Column('_political_aspects', sa.String(length=10), nullable=True),
    sa.Column('_short_term_revenue', sa.String(length=10), nullable=True),
    sa.Column('_long_term_revenue', sa.String(length=10), nullable=True),
    sa.Column('_risk', sa.String(length=10), nullable=True),
    sa.Column('_profitability', sa.String(length=10), nullable=True),
    sa.Column('_strategical_value', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['sales_project_fk'], ['salesproject._pk'], name=op.f('fk_ads_evaluation_sales_project_fk_salesproject'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_pk', name=op.f('pk_ads_evaluation'))
    )
    with op.batch_alter_table('ads_evaluation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_evaluation__access_to_funds'), ['_access_to_funds'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation__approach_decision_making_criteria'), ['_approach_decision_making_criteria'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation__credibility'), ['_credibility'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation__cultural_compatibility'), ['_cultural_compatibility'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation__current_relation_with_customer'), ['_current_relation_with_customer'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation__customer_business'), ['_customer_business'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation__customer_financials'), ['_customer_financials'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation__decisive_event'), ['_decisive_event'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation__disabled'), ['_disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation__final_applicability'), ['_final_applicability'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation__formal_decision_making_criteria'), ['_formal_decision_making_criteria'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation__internal_support'), ['_internal_support'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation__long_term_revenue'), ['_long_term_revenue'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation__political_aspects'), ['_political_aspects'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation__profitability'), ['_profitability'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation__resources_required_to_sell'), ['_resources_required_to_sell'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation__risk'), ['_risk'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation__short_term_revenue'), ['_short_term_revenue'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation__solution_matching'), ['_solution_matching'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation__strategical_value'), ['_strategical_value'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation__updated_by'), ['_updated_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation__value_of_business_proposal'), ['_value_of_business_proposal'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation_sales_project_fk'), ['sales_project_fk'], unique=True)

    op.create_table('ads_general_data',
    sa.Column('_pk', sa.String(length=36), nullable=False),
    sa.Column('_updated_by', sa.String(length=100), nullable=False),
    sa.Column('_updated_at', sa.DateTime(), nullable=False),
    sa.Column('_disabled', sa.Boolean(), nullable=False),
    sa.Column('sales_project_fk', sa.String(length=36), nullable=False),
    sa.Column('decisive_event', sa.String(length=100), nullable=True),
    sa.Column('competition', sa.String(length=100), nullable=True),
    sa.Column('potential_problems', sa.String(length=100), nullable=True),
    sa.Column('team_members', sa.String(length=100), nullable=True),
    sa.Column('client_company', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['sales_project_fk'], ['salesproject._pk'], name=op.f('fk_ads_general_data_sales_project_fk_salesproject'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_pk', name=op.f('pk_ads_general_data'))
    )
    with op.batch_alter_table('ads_general_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_general_data__disabled'), ['_disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_general_data__updated_by'), ['_updated_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_general_data_sales_project_fk'), ['sales_project_fk'], unique=True)

    op.create_table('ads_org_map',
    sa.Column('_pk', sa.String(length=36), nullable=False),
    sa.Column('_updated_by', sa.String(length=100), nullable=False),
    sa.Column('_updated_at', sa.DateTime(), nullable=False),
    sa.Column('_disabled', sa.Boolean(), nullable=False),
    sa.Column('sales_project_fk', sa.String(length=36), nullable=False),
    sa.Column('remarks', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['sales_project_fk'], ['salesproject._pk'], name=op.f('fk_ads_org_map_sales_project_fk_salesproject'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_pk', name=op.f('pk_ads_org_map'))
    )
    with op.batch_alter_table('ads_org_map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_org_map__disabled'), ['_disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_org_map__updated_by'), ['_updated_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_org_map_sales_project_fk'), ['sales_project_fk'], unique=True)

    op.create_table('ads_relationships',
    sa.Column('_pk', sa.String(length=36), nullable=False),
    sa.Column('_updated_by', sa.String(length=100), nullable=False),
    sa.Column('_updated_at', sa.DateTime(), nullable=False),
    sa.Column('_disabled', sa.Boolean(), nullable=False),
    sa.Column('sales_project_fk', sa.String(length=36), nullable=False),
    sa.Column('remarks', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['sales_project_fk'], ['salesproject._pk'], name=op.f('fk_ads_relationships_sales_project_fk_salesproject'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_pk', name=op.f('pk_ads_relationships'))
    )
    with op.batch_alter_table('ads_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_relationships__disabled'), ['_disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_relationships__updated_by'), ['_updated_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_relationships_sales_project_fk'), ['sales_project_fk'], unique=True)

    op.create_table('ads_revenue',
    sa.Column('_pk', sa.String(length=36), nullable=False),
    sa.Column('_updated_by', sa.String(length=100), nullable=False),
    sa.Column('_updated_at', sa.DateTime(), nullable=False),
    sa.Column('_disabled', sa.Boolean(), nullable=False),
    sa.Column('sales_project_fk', sa.String(length=36), nullable=False),
    sa.Column('remarks', sa.String(length=100), nullable=False),
    sa.Column('max_expected', sa.Float(), nullable=False),
    sa.Column('min_expected', sa.Float(), nullable=False),
    sa.Column('allocated_budget', sa.Float(), nullable=False),
    sa.Column('customer_min_expectation', sa.Float(), nullable=False),
    sa.Column('customer_max_expectation', sa.Float(), nullable=False),
    sa.Column('market_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['sales_project_fk'], ['salesproject._pk'], name=op.f('fk_ads_revenue_sales_project_fk_salesproject'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_pk', name=op.f('pk_ads_revenue'))
    )
    with op.batch_alter_table('ads_revenue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_revenue__disabled'), ['_disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_revenue__updated_by'), ['_updated_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_revenue_sales_project_fk'), ['sales_project_fk'], unique=True)

    op.create_table('ads_org_map_details',
    sa.Column('_pk', sa.String(length=36), nullable=False),
    sa.Column('_updated_by', sa.String(length=100), nullable=False),
    sa.Column('_updated_at', sa.DateTime(), nullable=False),
    sa.Column('_disabled', sa.Boolean(), nullable=False),
    sa.Column('ads_org_map_fk', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('decision_make', sa.Boolean(), nullable=False),
    sa.Column('need_to_sign', sa.Boolean(), nullable=False),
    sa.Column('technical_evaluation', sa.Boolean(), nullable=False),
    sa.Column('financial_evaluation', sa.Boolean(), nullable=False),
    sa.Column('consultant', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ads_org_map_fk'], ['ads_org_map._pk'], name=op.f('fk_ads_org_map_details_ads_org_map_fk_ads_org_map'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_pk', name=op.f('pk_ads_org_map_details')),
    sa.UniqueConstraint('code', 'ads_org_map_fk', name='uix_code_per_org_map')
    )
    with op.batch_alter_table('ads_org_map_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_org_map_details__disabled'), ['_disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_org_map_details__updated_by'), ['_updated_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_org_map_details_ads_org_map_fk'), ['ads_org_map_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_org_map_details_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_org_map_details_consultant'), ['consultant'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_org_map_details_decision_make'), ['decision_make'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_org_map_details_financial_evaluation'), ['financial_evaluation'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_org_map_details_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_org_map_details_need_to_sign'), ['need_to_sign'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_org_map_details_technical_evaluation'), ['technical_evaluation'], unique=False)

    op.create_table('ads_relationships_details',
    sa.Column('_pk', sa.String(length=36), nullable=False),
    sa.Column('_updated_by', sa.String(length=100), nullable=False),
    sa.Column('_updated_at', sa.DateTime(), nullable=False),
    sa.Column('_disabled', sa.Boolean(), nullable=False),
    sa.Column('ads_relationships_fk', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('position', sa.String(length=36), nullable=False),
    sa.Column('change_adaptability', sa.String(length=20), nullable=False),
    sa.Column('our_status_in_relation', sa.String(length=20), nullable=False),
    sa.Column('contact_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ads_relationships_fk'], ['ads_relationships._pk'], name=op.f('fk_ads_relationships_details_ads_relationships_fk_ads_relationships'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position'], ['ads_org_map_details._pk'], name=op.f('fk_ads_relationships_details_position_ads_org_map_details'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('_pk', name=op.f('pk_ads_relationships_details')),
    sa.UniqueConstraint('name', 'ads_relationships_fk', name='uix_name_per_org_map')
    )
    with op.batch_alter_table('ads_relationships_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_relationships_details__disabled'), ['_disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_relationships_details__updated_by'), ['_updated_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_relationships_details_ads_relationships_fk'), ['ads_relationships_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_relationships_details_change_adaptability'), ['change_adaptability'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_relationships_details_contact_status'), ['contact_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_relationships_details_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_relationships_details_our_status_in_relation'), ['our_status_in_relation'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_relationships_details_position'), ['position'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_relationships_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_relationships_details_position'))
        batch_op.drop_index(batch_op.f('ix_ads_relationships_details_our_status_in_relation'))
        batch_op.drop_index(batch_op.f('ix_ads_relationships_details_name'))
        batch_op.drop_index(batch_op.f('ix_ads_relationships_details_contact_status'))
        batch_op.drop_index(batch_op.f('ix_ads_relationships_details_change_adaptability'))
        batch_op.drop_index(batch_op.f('ix_ads_relationships_details_ads_relationships_fk'))
        batch_op.drop_index(batch_op.f('ix_ads_relationships_details__updated_by'))
        batch_op.drop_index(batch_op.f('ix_ads_relationships_details__disabled'))

    op.drop_table('ads_relationships_details')
    with op.batch_alter_table('ads_org_map_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_org_map_details_technical_evaluation'))
        batch_op.drop_index(batch_op.f('ix_ads_org_map_details_need_to_sign'))
        batch_op.drop_index(batch_op.f('ix_ads_org_map_details_name'))
        batch_op.drop_index(batch_op.f('ix_ads_org_map_details_financial_evaluation'))
        batch_op.drop_index(batch_op.f('ix_ads_org_map_details_decision_make'))
        batch_op.drop_index(batch_op.f('ix_ads_org_map_details_consultant'))
        batch_op.drop_index(batch_op.f('ix_ads_org_map_details_code'))
        batch_op.drop_index(batch_op.f('ix_ads_org_map_details_ads_org_map_fk'))
        batch_op.drop_index(batch_op.f('ix_ads_org_map_details__updated_by'))
        batch_op.drop_index(batch_op.f('ix_ads_org_map_details__disabled'))

    op.drop_table('ads_org_map_details')
    with op.batch_alter_table('ads_revenue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_revenue_sales_project_fk'))
        batch_op.drop_index(batch_op.f('ix_ads_revenue__updated_by'))
        batch_op.drop_index(batch_op.f('ix_ads_revenue__disabled'))

    op.drop_table('ads_revenue')
    with op.batch_alter_table('ads_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_relationships_sales_project_fk'))
        batch_op.drop_index(batch_op.f('ix_ads_relationships__updated_by'))
        batch_op.drop_index(batch_op.f('ix_ads_relationships__disabled'))

    op.drop_table('ads_relationships')
    with op.batch_alter_table('ads_org_map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_org_map_sales_project_fk'))
        batch_op.drop_index(batch_op.f('ix_ads_org_map__updated_by'))
        batch_op.drop_index(batch_op.f('ix_ads_org_map__disabled'))

    op.drop_table('ads_org_map')
    with op.batch_alter_table('ads_general_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_general_data_sales_project_fk'))
        batch_op.drop_index(batch_op.f('ix_ads_general_data__updated_by'))
        batch_op.drop_index(batch_op.f('ix_ads_general_data__disabled'))

    op.drop_table('ads_general_data')
    with op.batch_alter_table('ads_evaluation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_sales_project_fk'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation__value_of_business_proposal'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation__updated_by'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation__strategical_value'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation__solution_matching'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation__short_term_revenue'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation__risk'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation__resources_required_to_sell'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation__profitability'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation__political_aspects'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation__long_term_revenue'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation__internal_support'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation__formal_decision_making_criteria'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation__final_applicability'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation__disabled'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation__decisive_event'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation__customer_financials'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation__customer_business'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation__current_relation_with_customer'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation__cultural_compatibility'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation__credibility'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation__approach_decision_making_criteria'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation__access_to_funds'))

    op.drop_table('ads_evaluation')
    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solution__updated_by'))
        batch_op.drop_index(batch_op.f('ix_solution__disabled'))

    op.drop_table('solution')
    with op.batch_alter_table('salesproject', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salesproject_code'))
        batch_op.drop_index(batch_op.f('ix_salesproject__updated_by'))
        batch_op.drop_index(batch_op.f('ix_salesproject__disabled'))

    op.drop_table('salesproject')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company__updated_by'))
        batch_op.drop_index(batch_op.f('ix_company__disabled'))

    op.drop_table('company')
    # ### end Alembic commands ###
