"""empty message

Revision ID: c605c4fcdbb8
Revises: e0423b4fb15a
Create Date: 2023-02-28 18:11:10.618638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c605c4fcdbb8'
down_revision = 'e0423b4fb15a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_decision_criteria_details_2maptoperson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ads_relationships_details_fk', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_details_2maptoperson_ads_relationships_details_fk'), ['ads_relationships_details_fk'], unique=False)
        batch_op.create_unique_constraint('uix_person_per_criteria', ['ads_decision_criteria_details_1criterialist_fk', 'ads_relationships_details_fk'])
        batch_op.create_foreign_key(batch_op.f('fk_ads_decision_criteria_details_2maptoperson_ads_relationships_details_fk_ads_relationships_details'), 'ads_relationships_details', ['ads_relationships_details_fk'], ['_pk'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_decision_criteria_details_2maptoperson', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ads_decision_criteria_details_2maptoperson_ads_relationships_details_fk_ads_relationships_details'), type_='foreignkey')
        batch_op.drop_constraint('uix_person_per_criteria', type_='unique')
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_details_2maptoperson_ads_relationships_details_fk'))
        batch_op.drop_column('ads_relationships_details_fk')

    # ### end Alembic commands ###
