"""empty message

Revision ID: c80b12ddf13d
Revises: 3ae614995200
Create Date: 2023-03-23 05:34:37.512950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c80b12ddf13d'
down_revision = '3ae614995200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads_decision_criteria_version',
    sa.Column('_pk', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('_updated_by', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('_updated_at', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('_disabled', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('sales_project_fk', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('remarks', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('_pk', 'transaction_id', name=op.f('pk_ads_decision_criteria_version'))
    )
    with op.batch_alter_table('ads_decision_criteria_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_version__disabled'), ['_disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_version__updated_by'), ['_updated_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_version_remarks'), ['remarks'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_version_sales_project_fk'), ['sales_project_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('ads_general_data_version', schema=None) as batch_op:
        batch_op.alter_column('_updated_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('_updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('_disabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('sales_project_fk',
               existing_type=sa.VARCHAR(length=36),
               nullable=True,
               autoincrement=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_general_data_version', schema=None) as batch_op:
        batch_op.alter_column('sales_project_fk',
               existing_type=sa.VARCHAR(length=36),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('_disabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('_updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('_updated_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               autoincrement=False)

    with op.batch_alter_table('ads_decision_criteria_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_version_sales_project_fk'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_version_remarks'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_version_end_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_version__updated_by'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_version__disabled'))

    op.drop_table('ads_decision_criteria_version')
    # ### end Alembic commands ###
