"""empty message

Revision ID: d24e4a8eaaa2
Revises: 17167c147965
Create Date: 2023-03-23 06:01:05.757496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24e4a8eaaa2'
down_revision = '17167c147965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads_relationships_details_version',
    sa.Column('_pk', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('_updated_by', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('_updated_at', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('_disabled', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('ads_relationships_fk', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('position', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('change_adaptability', sa.String(length=20), autoincrement=False, nullable=False),
    sa.Column('our_status_in_relation', sa.String(length=20), autoincrement=False, nullable=False),
    sa.Column('contact_status', sa.String(length=20), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('_pk', 'transaction_id', name=op.f('pk_ads_relationships_details_version'))
    )
    with op.batch_alter_table('ads_relationships_details_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_relationships_details_version__disabled'), ['_disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_relationships_details_version__updated_by'), ['_updated_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_relationships_details_version_ads_relationships_fk'), ['ads_relationships_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_relationships_details_version_change_adaptability'), ['change_adaptability'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_relationships_details_version_contact_status'), ['contact_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_relationships_details_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_relationships_details_version_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_relationships_details_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_relationships_details_version_our_status_in_relation'), ['our_status_in_relation'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_relationships_details_version_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_relationships_details_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('ads_relationships_version',
    sa.Column('_pk', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('_updated_by', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('_updated_at', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('_disabled', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('sales_project_fk', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('remarks', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('_pk', 'transaction_id', name=op.f('pk_ads_relationships_version'))
    )
    with op.batch_alter_table('ads_relationships_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_relationships_version__disabled'), ['_disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_relationships_version__updated_by'), ['_updated_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_relationships_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_relationships_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_relationships_version_sales_project_fk'), ['sales_project_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_relationships_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('ads_org_map_details_version', schema=None) as batch_op:
        batch_op.alter_column('_updated_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('_updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('_disabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('ads_org_map_fk',
               existing_type=sa.VARCHAR(length=36),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('decision_make',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('need_to_sign',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('technical_evaluation',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('financial_evaluation',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('consultant',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)

    with op.batch_alter_table('ads_org_map_version', schema=None) as batch_op:
        batch_op.alter_column('_updated_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('_updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('_disabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('sales_project_fk',
               existing_type=sa.VARCHAR(length=36),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('remarks',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               autoincrement=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_org_map_version', schema=None) as batch_op:
        batch_op.alter_column('remarks',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('sales_project_fk',
               existing_type=sa.VARCHAR(length=36),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('_disabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('_updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('_updated_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               autoincrement=False)

    with op.batch_alter_table('ads_org_map_details_version', schema=None) as batch_op:
        batch_op.alter_column('consultant',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('financial_evaluation',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('technical_evaluation',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('need_to_sign',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('decision_make',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('ads_org_map_fk',
               existing_type=sa.VARCHAR(length=36),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('_disabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('_updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('_updated_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               autoincrement=False)

    with op.batch_alter_table('ads_relationships_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_relationships_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ads_relationships_version_sales_project_fk'))
        batch_op.drop_index(batch_op.f('ix_ads_relationships_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_ads_relationships_version_end_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ads_relationships_version__updated_by'))
        batch_op.drop_index(batch_op.f('ix_ads_relationships_version__disabled'))

    op.drop_table('ads_relationships_version')
    with op.batch_alter_table('ads_relationships_details_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_relationships_details_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ads_relationships_details_version_position'))
        batch_op.drop_index(batch_op.f('ix_ads_relationships_details_version_our_status_in_relation'))
        batch_op.drop_index(batch_op.f('ix_ads_relationships_details_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_ads_relationships_details_version_name'))
        batch_op.drop_index(batch_op.f('ix_ads_relationships_details_version_end_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ads_relationships_details_version_contact_status'))
        batch_op.drop_index(batch_op.f('ix_ads_relationships_details_version_change_adaptability'))
        batch_op.drop_index(batch_op.f('ix_ads_relationships_details_version_ads_relationships_fk'))
        batch_op.drop_index(batch_op.f('ix_ads_relationships_details_version__updated_by'))
        batch_op.drop_index(batch_op.f('ix_ads_relationships_details_version__disabled'))

    op.drop_table('ads_relationships_details_version')
    # ### end Alembic commands ###
