"""empty message

Revision ID: d45f91162cb9
Revises: 8cd9cf010bcb
Create Date: 2023-02-28 13:41:21.777625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd45f91162cb9'
down_revision = '8cd9cf010bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_decision_criteria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_project_fk', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('our_status', sa.String(length=20), nullable=False))
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_our_status'), ['our_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_sales_project_fk'), ['sales_project_fk'], unique=True)
        batch_op.create_foreign_key(batch_op.f('fk_ads_decision_criteria_sales_project_fk_salesproject'), 'salesproject', ['sales_project_fk'], ['_pk'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_decision_criteria', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ads_decision_criteria_sales_project_fk_salesproject'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_sales_project_fk'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_our_status'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_name'))
        batch_op.drop_column('our_status')
        batch_op.drop_column('name')
        batch_op.drop_column('sales_project_fk')

    # ### end Alembic commands ###
