"""empty message

Revision ID: d9348954494c
Revises: c80b12ddf13d
Create Date: 2023-03-23 05:38:32.864811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9348954494c'
down_revision = 'c80b12ddf13d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads_evaluation_version',
    sa.Column('_pk', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('_updated_by', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('_updated_at', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('_disabled', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('sales_project_fk', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('remarks', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('_final_applicability', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('_customer_business', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('_customer_financials', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('_access_to_funds', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('_decisive_event', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('_formal_decision_making_criteria', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('_solution_matching', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('_resources_required_to_sell', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('_current_relation_with_customer', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('_value_of_business_proposal', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('_internal_support', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('_credibility', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('_cultural_compatibility', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('_approach_decision_making_criteria', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('_political_aspects', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('_short_term_revenue', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('_long_term_revenue', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('_risk', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('_profitability', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('_strategical_value', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('_pk', 'transaction_id', name=op.f('pk_ads_evaluation_version'))
    )
    with op.batch_alter_table('ads_evaluation_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_evaluation_version__access_to_funds'), ['_access_to_funds'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation_version__approach_decision_making_criteria'), ['_approach_decision_making_criteria'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation_version__credibility'), ['_credibility'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation_version__cultural_compatibility'), ['_cultural_compatibility'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation_version__current_relation_with_customer'), ['_current_relation_with_customer'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation_version__customer_business'), ['_customer_business'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation_version__customer_financials'), ['_customer_financials'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation_version__decisive_event'), ['_decisive_event'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation_version__disabled'), ['_disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation_version__final_applicability'), ['_final_applicability'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation_version__formal_decision_making_criteria'), ['_formal_decision_making_criteria'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation_version__internal_support'), ['_internal_support'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation_version__long_term_revenue'), ['_long_term_revenue'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation_version__political_aspects'), ['_political_aspects'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation_version__profitability'), ['_profitability'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation_version__resources_required_to_sell'), ['_resources_required_to_sell'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation_version__risk'), ['_risk'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation_version__short_term_revenue'), ['_short_term_revenue'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation_version__solution_matching'), ['_solution_matching'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation_version__strategical_value'), ['_strategical_value'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation_version__updated_by'), ['_updated_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation_version__value_of_business_proposal'), ['_value_of_business_proposal'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation_version_sales_project_fk'), ['sales_project_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_evaluation_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('ads_decision_criteria_version', schema=None) as batch_op:
        batch_op.alter_column('_updated_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('_updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('_disabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('sales_project_fk',
               existing_type=sa.VARCHAR(length=36),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('remarks',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               autoincrement=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_decision_criteria_version', schema=None) as batch_op:
        batch_op.alter_column('remarks',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('sales_project_fk',
               existing_type=sa.VARCHAR(length=36),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('_disabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('_updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('_updated_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               autoincrement=False)

    with op.batch_alter_table('ads_evaluation_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_version_sales_project_fk'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_version_end_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_version__value_of_business_proposal'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_version__updated_by'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_version__strategical_value'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_version__solution_matching'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_version__short_term_revenue'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_version__risk'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_version__resources_required_to_sell'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_version__profitability'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_version__political_aspects'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_version__long_term_revenue'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_version__internal_support'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_version__formal_decision_making_criteria'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_version__final_applicability'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_version__disabled'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_version__decisive_event'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_version__customer_financials'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_version__customer_business'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_version__current_relation_with_customer'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_version__cultural_compatibility'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_version__credibility'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_version__approach_decision_making_criteria'))
        batch_op.drop_index(batch_op.f('ix_ads_evaluation_version__access_to_funds'))

    op.drop_table('ads_evaluation_version')
    # ### end Alembic commands ###
