"""empty message

Revision ID: e0423b4fb15a
Revises: 8cf38fde5734
Create Date: 2023-02-28 17:37:31.037680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0423b4fb15a'
down_revision = '8cf38fde5734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_decision_criteria_details_2maptoperson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ads_decision_criteria_details_1criterialist_fk', sa.String(length=36), nullable=False))
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_details_2maptoperson_ads_decision_criteria_details_1criterialist_fk'), ['ads_decision_criteria_details_1criterialist_fk'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_ads_decision_criteria_details_2maptoperson_ads_decision_criteria_details_1criterialist_fk_ads_decision_criteria_details_1criterialist'), 'ads_decision_criteria_details_1criterialist', ['ads_decision_criteria_details_1criterialist_fk'], ['_pk'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_decision_criteria_details_2maptoperson', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ads_decision_criteria_details_2maptoperson_ads_decision_criteria_details_1criterialist_fk_ads_decision_criteria_details_1criterialist'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_details_2maptoperson_ads_decision_criteria_details_1criterialist_fk'))
        batch_op.drop_column('ads_decision_criteria_details_1criterialist_fk')

    # ### end Alembic commands ###
