"""empty message

Revision ID: f643ace9fd49
Revises: 9ba3cfcb2fa7
Create Date: 2023-03-23 06:15:38.685528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f643ace9fd49'
down_revision = '9ba3cfcb2fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads_decision_criteria_details_1criterialist_version',
    sa.Column('_pk', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('_updated_by', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('_updated_at', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('_disabled', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('ads_decision_criteria_fk', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('our_status', sa.String(length=20), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('_pk', 'transaction_id', name=op.f('pk_ads_decision_criteria_details_1criterialist_version'))
    )
    with op.batch_alter_table('ads_decision_criteria_details_1criterialist_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_details_1criterialist_version__disabled'), ['_disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_details_1criterialist_version__updated_by'), ['_updated_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_details_1criterialist_version_ads_decision_criteria_fk'), ['ads_decision_criteria_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_details_1criterialist_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_details_1criterialist_version_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_details_1criterialist_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_details_1criterialist_version_our_status'), ['our_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_details_1criterialist_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('ads_decision_criteria_details_2maptoperson_version',
    sa.Column('_pk', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('_updated_by', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('_updated_at', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('_disabled', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('ads_decision_criteria_details_1criterialist_fk', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('ads_relationships_details_fk', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('client_importance', sa.String(length=20), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('_pk', 'transaction_id', name=op.f('pk_ads_decision_criteria_details_2maptoperson_version'))
    )
    with op.batch_alter_table('ads_decision_criteria_details_2maptoperson_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_details_2maptoperson_version__disabled'), ['_disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_details_2maptoperson_version__updated_by'), ['_updated_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_details_2maptoperson_version_ads_decision_criteria_details_1criterialist_fk'), ['ads_decision_criteria_details_1criterialist_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_details_2maptoperson_version_ads_relationships_details_fk'), ['ads_relationships_details_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_details_2maptoperson_version_client_importance'), ['client_importance'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_details_2maptoperson_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_details_2maptoperson_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_decision_criteria_details_2maptoperson_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('ads_solution_details_version',
    sa.Column('_pk', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('_updated_by', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('_updated_at', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('_disabled', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('ads_solution_fk', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('strength', sa.String(length=20), autoincrement=False, nullable=False),
    sa.Column('feature_type', sa.String(length=20), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('_pk', 'transaction_id', name=op.f('pk_ads_solution_details_version'))
    )
    with op.batch_alter_table('ads_solution_details_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_solution_details_version__disabled'), ['_disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_solution_details_version__updated_by'), ['_updated_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_solution_details_version_ads_solution_fk'), ['ads_solution_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_solution_details_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_solution_details_version_feature_type'), ['feature_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_solution_details_version_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_solution_details_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_solution_details_version_strength'), ['strength'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_solution_details_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('ads_solution_version',
    sa.Column('_pk', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('_updated_by', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('_updated_at', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('_disabled', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('sales_project_fk', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('remarks', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('_pk', 'transaction_id', name=op.f('pk_ads_solution_version'))
    )
    with op.batch_alter_table('ads_solution_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_solution_version__disabled'), ['_disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_solution_version__updated_by'), ['_updated_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_solution_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_solution_version_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_solution_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_solution_version_sales_project_fk'), ['sales_project_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_solution_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('ads_revenue_version', schema=None) as batch_op:
        batch_op.alter_column('_updated_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('_updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('_disabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('sales_project_fk',
               existing_type=sa.VARCHAR(length=36),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('remarks',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('max_expected',
               existing_type=sa.FLOAT(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('min_expected',
               existing_type=sa.FLOAT(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('allocated_budget',
               existing_type=sa.FLOAT(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('customer_min_expectation',
               existing_type=sa.FLOAT(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('customer_max_expectation',
               existing_type=sa.FLOAT(),
               nullable=True,
               autoincrement=False)
        batch_op.alter_column('market_price',
               existing_type=sa.FLOAT(),
               nullable=True,
               autoincrement=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_revenue_version', schema=None) as batch_op:
        batch_op.alter_column('market_price',
               existing_type=sa.FLOAT(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('customer_max_expectation',
               existing_type=sa.FLOAT(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('customer_min_expectation',
               existing_type=sa.FLOAT(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('allocated_budget',
               existing_type=sa.FLOAT(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('min_expected',
               existing_type=sa.FLOAT(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('max_expected',
               existing_type=sa.FLOAT(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('remarks',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('sales_project_fk',
               existing_type=sa.VARCHAR(length=36),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('_disabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('_updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               autoincrement=False)
        batch_op.alter_column('_updated_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               autoincrement=False)

    with op.batch_alter_table('ads_solution_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_solution_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ads_solution_version_sales_project_fk'))
        batch_op.drop_index(batch_op.f('ix_ads_solution_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_ads_solution_version_name'))
        batch_op.drop_index(batch_op.f('ix_ads_solution_version_end_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ads_solution_version__updated_by'))
        batch_op.drop_index(batch_op.f('ix_ads_solution_version__disabled'))

    op.drop_table('ads_solution_version')
    with op.batch_alter_table('ads_solution_details_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_solution_details_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ads_solution_details_version_strength'))
        batch_op.drop_index(batch_op.f('ix_ads_solution_details_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_ads_solution_details_version_name'))
        batch_op.drop_index(batch_op.f('ix_ads_solution_details_version_feature_type'))
        batch_op.drop_index(batch_op.f('ix_ads_solution_details_version_end_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ads_solution_details_version_ads_solution_fk'))
        batch_op.drop_index(batch_op.f('ix_ads_solution_details_version__updated_by'))
        batch_op.drop_index(batch_op.f('ix_ads_solution_details_version__disabled'))

    op.drop_table('ads_solution_details_version')
    with op.batch_alter_table('ads_decision_criteria_details_2maptoperson_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_details_2maptoperson_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_details_2maptoperson_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_details_2maptoperson_version_end_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_details_2maptoperson_version_client_importance'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_details_2maptoperson_version_ads_relationships_details_fk'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_details_2maptoperson_version_ads_decision_criteria_details_1criterialist_fk'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_details_2maptoperson_version__updated_by'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_details_2maptoperson_version__disabled'))

    op.drop_table('ads_decision_criteria_details_2maptoperson_version')
    with op.batch_alter_table('ads_decision_criteria_details_1criterialist_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_details_1criterialist_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_details_1criterialist_version_our_status'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_details_1criterialist_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_details_1criterialist_version_name'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_details_1criterialist_version_end_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_details_1criterialist_version_ads_decision_criteria_fk'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_details_1criterialist_version__updated_by'))
        batch_op.drop_index(batch_op.f('ix_ads_decision_criteria_details_1criterialist_version__disabled'))

    op.drop_table('ads_decision_criteria_details_1criterialist_version')
    # ### end Alembic commands ###
